### PR TITLE
Login page and register page

### PR DESCRIPTION
**Pull request by jaime-deng**
The files are inside of the layout folder and need to be implemented in our application.

### CODE REVIEW

**Comment by emo8355** [comment]
hey jaime, can you change the branch you merging to the devver3 ?

**Comment by jaime-deng** [comment]
Do you want me to merge to devver3?

**Comment by emo8355** [comment]
> Do you want me to merge to devver3?

yes, please

**Comment by jaime-deng** [comment]
Okay I make a pull request

**Pull request closed without merging**
